// AUTO-GENERATED from @figma/plugin-typings by scripts/gen-node-fields.ts.
// Do not edit by hand — run `bun run gen:node-fields`.

// Data fields safe to read directly via node[key] (no node-reference host objects).
export const NODE_DATA_FIELDS: ReadonlyArray<string> = [
    "absoluteBoundingBox",
    "absoluteRenderBounds",
    "absoluteTransform",
    "annotations",
    "arcData",
    "authorName",
    "authorVisible",
    "autoRename",
    "backgroundStyleId",
    "backgrounds",
    "blendMode",
    "booleanOperation",
    "bottomLeftRadius",
    "bottomRightRadius",
    "boundVariables",
    "characters",
    "clipsContent",
    "code",
    "codeLanguage",
    "complexStrokeProperties",
    "componentProperties",
    "componentPropertyDefinitions",
    "componentPropertyReferences",
    "connectorEnd",
    "connectorEndStrokeCap",
    "connectorLineType",
    "connectorStart",
    "connectorStartStrokeCap",
    "constrainProportions",
    "constraints",
    "cornerRadius",
    "cornerSmoothing",
    "counterAxisAlignContent",
    "counterAxisAlignItems",
    "counterAxisSizingMode",
    "counterAxisSpacing",
    "dashPattern",
    "description",
    "descriptionMarkdown",
    "detachedInfo",
    "devStatus",
    "documentationLinks",
    "effectStyleId",
    "effects",
    "embedData",
    "expanded",
    "explicitVariableModes",
    "exportSettings",
    "fillGeometry",
    "fillStyleId",
    "fills",
    "fontName",
    "fontSize",
    "fontWeight",
    "gridChildHorizontalAlign",
    "gridChildVerticalAlign",
    "gridColumnAnchorIndex",
    "gridColumnCount",
    "gridColumnGap",
    "gridColumnSizes",
    "gridColumnSpan",
    "gridRowAnchorIndex",
    "gridRowCount",
    "gridRowGap",
    "gridRowSizes",
    "gridRowSpan",
    "gridStyleId",
    "guides",
    "handleMirroring",
    "hangingList",
    "hangingPunctuation",
    "hasMissingFont",
    "height",
    "horizontalPadding",
    "hyperlink",
    "inferredAutoLayout",
    "inferredVariables",
    "innerRadius",
    "interactiveSlideElementType",
    "isAsset",
    "isExposedInstance",
    "isMask",
    "isSkippedSlide",
    "isWideWidth",
    "itemReverseZIndex",
    "itemSpacing",
    "key",
    "layoutAlign",
    "layoutGrids",
    "layoutGrow",
    "layoutMode",
    "layoutPositioning",
    "layoutSizingHorizontal",
    "layoutSizingVertical",
    "layoutWrap",
    "leadingTrim",
    "letterSpacing",
    "lineHeight",
    "linkUnfurlData",
    "listSpacing",
    "locked",
    "maskType",
    "maxHeight",
    "maxLines",
    "maxWidth",
    "mediaData",
    "minHeight",
    "minWidth",
    "numColumns",
    "numRows",
    "numberOfFixedChildren",
    "opacity",
    "openTypeFeatures",
    "overflowDirection",
    "overlayBackground",
    "overlayBackgroundInteraction",
    "overlayPositionType",
    "overrides",
    "paddingBottom",
    "paddingLeft",
    "paddingRight",
    "paddingTop",
    "paragraphIndent",
    "paragraphSpacing",
    "pointCount",
    "primaryAxisAlignItems",
    "primaryAxisSizingMode",
    "reactions",
    "relativeTransform",
    "remote",
    "removed",
    "resolvedVariableModes",
    "rotation",
    "scaleFactor",
    "sectionContentsHidden",
    "shapeType",
    "strokeAlign",
    "strokeBottomWeight",
    "strokeCap",
    "strokeGeometry",
    "strokeJoin",
    "strokeLeftWeight",
    "strokeMiterLimit",
    "strokeRightWeight",
    "strokeStyleId",
    "strokeTopWeight",
    "strokeWeight",
    "strokes",
    "strokesIncludedInLayout",
    "targetAspectRatio",
    "textAlignHorizontal",
    "textAlignVertical",
    "textAutoResize",
    "textCase",
    "textDecoration",
    "textDecorationColor",
    "textDecorationOffset",
    "textDecorationSkipInk",
    "textDecorationStyle",
    "textDecorationThickness",
    "textPathStartData",
    "textStyleId",
    "textTruncation",
    "topLeftRadius",
    "topRightRadius",
    "transformModifiers",
    "variableWidthStrokeProperties",
    "variantGroupProperties",
    "variantProperties",
    "vectorNetwork",
    "vectorPaths",
    "verticalPadding",
    "visible",
    "widgetId",
    "widgetSyncedState",
    "width",
    "x",
    "y",
];

// Every node field (data + reference) → its TypeScript type, for documentation.
export const NODE_FIELD_TYPES: Readonly<Record<string, string>> = {
    "absoluteBoundingBox": "Rect | null",
    "absoluteRenderBounds": "Rect | null",
    "absoluteTransform": "Transform",
    "annotations": "readonly Annotation[]",
    "arcData": "ArcData",
    "attachedConnectors": "ConnectorNode[]",
    "authorName": "string",
    "authorVisible": "boolean",
    "autoRename": "boolean",
    "backgroundStyleId": "string",
    "backgrounds": "readonly Paint[]",
    "blendMode": "BlendMode",
    "booleanOperation": "\"UNION\" | \"INTERSECT\" | \"SUBTRACT\" | \"EXCLUDE\"",
    "bottomLeftRadius": "number",
    "bottomRightRadius": "number",
    "boundVariables": "({ readonly visible?: VariableAlias | undefined; readonly characters?: VariableAlias | undefined; readonly height?: VariableAlias | undefined; ... 22 more ...; readonly gridColumnGap?: VariableAlias | undefined; } & { ...; } & { ...; }) | undefined",
    "characters": "string",
    "children": "readonly SceneNode[]",
    "clipsContent": "boolean",
    "code": "string",
    "codeLanguage": "\"RUBY\" | \"TYPESCRIPT\" | \"CPP\" | \"CSS\" | \"JAVASCRIPT\" | \"HTML\" | \"JSON\" | \"GRAPHQL\" | \"PYTHON\" | \"GO\" | \"SQL\" | \"SWIFT\" | \"KOTLIN\" | \"RUST\" | \"BASH\" | \"PLAINTEXT\" | \"DART\"",
    "complexStrokeProperties": "ComplexStrokeProperties",
    "componentProperties": "ComponentProperties",
    "componentPropertyDefinitions": "ComponentPropertyDefinitions",
    "componentPropertyReferences": "{ visible?: string | undefined; characters?: string | undefined; mainComponent?: string | undefined; } | null",
    "connectorEnd": "ConnectorEndpoint",
    "connectorEndStrokeCap": "ConnectorStrokeCap",
    "connectorLineType": "\"ELBOWED\" | \"STRAIGHT\" | \"CURVED\"",
    "connectorStart": "ConnectorEndpoint",
    "connectorStartStrokeCap": "ConnectorStrokeCap",
    "constrainProportions": "boolean",
    "constraints": "Constraints",
    "cornerRadius": "number | unique symbol",
    "cornerSmoothing": "number",
    "counterAxisAlignContent": "\"AUTO\" | \"SPACE_BETWEEN\"",
    "counterAxisAlignItems": "\"MIN\" | \"CENTER\" | \"MAX\" | \"BASELINE\"",
    "counterAxisSizingMode": "\"FIXED\" | \"AUTO\"",
    "counterAxisSpacing": "number | null",
    "dashPattern": "readonly number[]",
    "defaultVariant": "ComponentNode",
    "description": "string",
    "descriptionMarkdown": "string",
    "detachedInfo": "DetachedInfo | null",
    "devStatus": "DevStatus",
    "documentationLinks": "readonly DocumentationLink[]",
    "effectStyleId": "string",
    "effects": "readonly Effect[]",
    "embedData": "EmbedData",
    "expanded": "boolean",
    "explicitVariableModes": "{ [collectionId: string]: string; }",
    "exportSettings": "readonly ExportSettings[]",
    "exposedInstances": "InstanceNode[]",
    "fillGeometry": "VectorPaths",
    "fillStyleId": "string | unique symbol",
    "fills": "readonly Paint[] | unique symbol",
    "fontName": "unique symbol | FontName",
    "fontSize": "number | unique symbol",
    "fontWeight": "number | unique symbol",
    "gridChildHorizontalAlign": "\"MIN\" | \"CENTER\" | \"MAX\" | \"AUTO\"",
    "gridChildVerticalAlign": "\"MIN\" | \"CENTER\" | \"MAX\" | \"AUTO\"",
    "gridColumnAnchorIndex": "number",
    "gridColumnCount": "number",
    "gridColumnGap": "number",
    "gridColumnSizes": "GridTrackSize[]",
    "gridColumnSpan": "number",
    "gridRowAnchorIndex": "number",
    "gridRowCount": "number",
    "gridRowGap": "number",
    "gridRowSizes": "GridTrackSize[]",
    "gridRowSpan": "number",
    "gridStyleId": "string",
    "guides": "readonly Guide[]",
    "handleMirroring": "unique symbol | HandleMirroring",
    "hangingList": "boolean",
    "hangingPunctuation": "boolean",
    "hasMissingFont": "boolean",
    "height": "number",
    "horizontalPadding": "number",
    "hyperlink": "unique symbol | HyperlinkTarget | null",
    "id": "string",
    "inferredAutoLayout": "InferredAutoLayoutResult | null",
    "inferredVariables": "({ readonly visible?: VariableAlias[] | undefined; readonly characters?: VariableAlias[] | undefined; readonly height?: VariableAlias[] | undefined; ... 22 more ...; readonly gridColumnGap?: VariableAlias[] | undefined; } & { ...; }) | undefined",
    "innerRadius": "number",
    "instances": "InstanceNode[]",
    "interactiveSlideElementType": "\"POLL\" | \"EMBED\" | \"FACEPILE\" | \"ALIGNMENT\" | \"YOUTUBE\"",
    "isAsset": "boolean",
    "isExposedInstance": "boolean",
    "isMask": "boolean",
    "isSkippedSlide": "boolean",
    "isWideWidth": "boolean",
    "itemReverseZIndex": "boolean",
    "itemSpacing": "number",
    "key": "string",
    "layoutAlign": "\"MIN\" | \"CENTER\" | \"MAX\" | \"STRETCH\" | \"INHERIT\"",
    "layoutGrids": "readonly LayoutGrid[]",
    "layoutGrow": "number",
    "layoutMode": "\"NONE\" | \"HORIZONTAL\" | \"VERTICAL\" | \"GRID\"",
    "layoutPositioning": "\"AUTO\" | \"ABSOLUTE\"",
    "layoutSizingHorizontal": "\"FIXED\" | \"HUG\" | \"FILL\"",
    "layoutSizingVertical": "\"FIXED\" | \"HUG\" | \"FILL\"",
    "layoutWrap": "\"NO_WRAP\" | \"WRAP\"",
    "leadingTrim": "unique symbol | LeadingTrim",
    "letterSpacing": "unique symbol | LetterSpacing",
    "lineHeight": "unique symbol | LineHeight",
    "linkUnfurlData": "LinkUnfurlData",
    "listSpacing": "number",
    "locked": "boolean",
    "mainComponent": "ComponentNode | null",
    "maskType": "MaskType",
    "maxHeight": "number | null",
    "maxLines": "number | null",
    "maxWidth": "number | null",
    "mediaData": "MediaData",
    "minHeight": "number | null",
    "minWidth": "number | null",
    "name": "string",
    "numColumns": "number",
    "numRows": "number",
    "numberOfFixedChildren": "number",
    "opacity": "number",
    "openTypeFeatures": "unique symbol | { readonly PCAP: boolean; readonly C2PC: boolean; readonly CASE: boolean; readonly CPSP: boolean; readonly TITL: boolean; readonly UNIC: boolean; readonly ZERO: boolean; ... 221 more ...; readonly CV99: boolean; }",
    "overflowDirection": "OverflowDirection",
    "overlayBackground": "OverlayBackground",
    "overlayBackgroundInteraction": "OverlayBackgroundInteraction",
    "overlayPositionType": "OverlayPositionType",
    "overrides": "{ id: string; overriddenFields: NodeChangeProperty[]; }[]",
    "paddingBottom": "number",
    "paddingLeft": "number",
    "paddingRight": "number",
    "paddingTop": "number",
    "paragraphIndent": "number",
    "paragraphSpacing": "number",
    "parent": "(BaseNode & ChildrenMixin) | null",
    "pointCount": "number",
    "primaryAxisAlignItems": "\"MIN\" | \"CENTER\" | \"MAX\" | \"SPACE_BETWEEN\"",
    "primaryAxisSizingMode": "\"FIXED\" | \"AUTO\"",
    "reactions": "readonly Reaction[]",
    "relativeTransform": "Transform",
    "remote": "boolean",
    "removed": "boolean",
    "resolvedVariableModes": "{ [collectionId: string]: string; }",
    "rotation": "number",
    "scaleFactor": "number",
    "sectionContentsHidden": "boolean",
    "shapeType": "\"SQUARE\" | \"ELLIPSE\" | \"ROUNDED_RECTANGLE\" | \"DIAMOND\" | \"TRIANGLE_UP\" | \"TRIANGLE_DOWN\" | \"PARALLELOGRAM_RIGHT\" | \"PARALLELOGRAM_LEFT\" | \"ENG_DATABASE\" | \"ENG_QUEUE\" | \"ENG_FILE\" | ... 18 more ... | \"INTERNAL_STORAGE\"",
    "strokeAlign": "\"CENTER\" | \"INSIDE\" | \"OUTSIDE\"",
    "strokeBottomWeight": "number",
    "strokeCap": "StrokeCap | unique symbol",
    "strokeGeometry": "VectorPaths",
    "strokeJoin": "unique symbol | StrokeJoin",
    "strokeLeftWeight": "number",
    "strokeMiterLimit": "number",
    "strokeRightWeight": "number",
    "strokeStyleId": "string",
    "strokeTopWeight": "number",
    "strokeWeight": "number | unique symbol",
    "strokes": "readonly Paint[]",
    "strokesIncludedInLayout": "boolean",
    "stuckNodes": "SceneNode[]",
    "stuckTo": "SceneNode | null",
    "targetAspectRatio": "Vector | null",
    "text": "TextSublayerNode",
    "textAlignHorizontal": "\"CENTER\" | \"LEFT\" | \"RIGHT\" | \"JUSTIFIED\"",
    "textAlignVertical": "\"CENTER\" | \"TOP\" | \"BOTTOM\"",
    "textAutoResize": "\"NONE\" | \"WIDTH_AND_HEIGHT\" | \"HEIGHT\" | \"TRUNCATE\"",
    "textBackground": "LabelSublayerNode",
    "textCase": "unique symbol | TextCase",
    "textDecoration": "unique symbol | TextDecoration",
    "textDecorationColor": "unique symbol | TextDecorationColor | null",
    "textDecorationOffset": "unique symbol | TextDecorationOffset | null",
    "textDecorationSkipInk": "boolean | unique symbol | null",
    "textDecorationStyle": "unique symbol | TextDecorationStyle | null",
    "textDecorationThickness": "unique symbol | TextDecorationThickness | null",
    "textPathStartData": "TextPathStartData",
    "textStyleId": "string | unique symbol",
    "textTruncation": "\"DISABLED\" | \"ENDING\"",
    "topLeftRadius": "number",
    "topRightRadius": "number",
    "transformModifiers": "TransformModifier[]",
    "type": "\"SLICE\"",
    "variableWidthStrokeProperties": "VariableWidthStrokeProperties | null",
    "variantGroupProperties": "{ [property: string]: { values: string[]; }; }",
    "variantProperties": "{ [property: string]: string; } | null",
    "vectorNetwork": "VectorNetwork",
    "vectorPaths": "VectorPaths",
    "verticalPadding": "number",
    "visible": "boolean",
    "widgetId": "string",
    "widgetSyncedState": "{ [key: string]: any; }",
    "width": "number",
    "x": "number",
    "y": "number",
};
